# https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml

plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

require:
  - rubocop-packaging

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1


# Layout
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 200


# Style
Style/ClassAndModuleChildren:
  Exclude:
    - Guardfile

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
